# 应用服务 WEB 访问端口
server:
  port: 8081
  resources:
    static-locations: classpath:/resources/,classpath:/static/


#IAM服务地址  需要替换ip+port为已知IAM服务地址
iam:
  token:
    path: http://ip:port


#访问静态资源
spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

