server:
  port: 8080

# logback??
logback:
  path: ..//logs/${spring.application.name}
spring:
  application:
    name: mock-demo

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wyci.gabapidemo
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


# logbook配置
logbook:
  exclude:
  #    - /auth/api/v1/function/qr_code
  #    - /auth/api/v1/function/query_qr
  # include:
  #   - /auth/**
  format:
    style: http
  write:
    chunk-size: 10000
    level: info
    max-body-size: 10000
  obfuscate:
    headers:
    parameters:
      - password
#    write:
#      chunk-size: 1000