# ????
logging:
  #????????
  config: classpath:logback-spring.xml

# logback??
logback:
  path: ../logs/${spring.application.name}
spring:
  application:
    name: log-demo



# logbook配置
logbook:
  exclude:
#    - /auth/api/v1/function/qr_code
#    - /auth/api/v1/function/query_qr
  # include:
  #   - /auth/**
  format:
    style: http
  write:
    chunk-size: 10000
    level: info
    max-body-size: 10000
  obfuscate:
    headers:
    parameters:
      - password
#    write:
#      chunk-size: 1000