demo:
  redis:
    enabled: true
    ip: 10.3.44.15
    port: 6379
    password: eetrust
    connectionTimeout: 2000
    soTimeout: 2000
    defaultTime: 1800
    cacheInfoList:
#      - key: cacheable
#        time: -1
      - key: test
        time: 200

