demo:
  redis:
    enabled: true
    ip: 127.0.0.1
    port: 6379
    password:
    connectionTimeout: 2000
    soTimeout: 2000
    defaultTime: 1800
    cacheInfoList:
#      - key: cacheable
#        time: -1
      - key: test
        time: 200

